### ISSUE TITLE
卖出功能建议

### ISSUE THREAD

**Issue by yejr** [tokenbankteam/feedback#8]
hi 我是TP钱包使用者，首先感谢你们的产品。
我有个关于该app产品的建议：
希望app能有个功能，设置最低保留内存数值。
其作用是，在卖出时，选择100%卖出后，也能自动保留相应预留内存数，不至于总是提示剩余内存不足，得手动反复调整。

这个建议希望考虑下，再次感谢。

**Comment by heipacker** [comment]
非常感谢您的建议， 这个功能我们在下一个版本会加上。
